image:
    - Visual Studio 2015

environment:
  global:
    VSVER: 14
    ARCH: x86

version: VC$(vsver)-$(arch).{build}

build:
  parallel: true
  verbosity: detailed

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio "%VSVER%".0\VC\vcvarsall.bat" %ARCH%
  - echo "MuPDF BUILD %APPVEYOR_BUILD_VERSION%_%VSVER%_%ARCH%"

build_script:
  - echo "Recursively clone mupdf..."
  - git clone --recursive git://git.ghostscript.com/mupdf.git
  - cd mupdf\platform\win32
  - echo "Upgrade all project files (maybe it takes > 10min), please wait..."
  - devenv /upgrade mupdf.sln
  - timeout /t 60
  - msbuild /m mupdf.sln /property:Configuration=Release

after_build:
   - 7z a %APPVEYOR_BUILD_FOLDER%\mupdf\platform\win32\Release\*.lib %APPVEYOR_BUILD_FOLDER%\MuPDF-lib-vc%VSVER%_%ARCH%.zip
   - 7z a %APPVEYOR_BUILD_FOLDER%\mupdf\platform\win32\Release\*.exe %APPVEYOR_BUILD_FOLDER%\MuPDF-bin-vc%VSVER%_%ARCH%.zip

artifacts:
   - path: MuPDF-lib-vc%VSVER%_%ARCH%.zip
   - path: MuPDF-bin-vc%VSVER%_%ARCH%.zip

# remote desktop connection on init
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# remote desktop connection on finish and block build to not destroy VM
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
